# Generated by Django 4.2.5 on 2023-09-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumno_fk_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno_has_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Alumno', models.ForeignKey(db_column='fk_alumno', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_Genero', models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
