# Generated by Django 4.2.5 on 2023-10-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
    ]
