# Generated by Django 4.2.5 on 2023-10-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registrarform_delete_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrarform',
            table='Registrar',
        ),
    ]
