# Generated by Django 4.2.5 on 2023-10-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_registrarform_id_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Genero',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Alumno_has_Genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
