# Generated by Django 4.2.5 on 2023-10-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_alumno_has_genero_fk_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarform',
            name='apellidos_us',
        ),
        migrations.RemoveField(
            model_name='registrarform',
            name='nombre_us',
        ),
        migrations.AddField(
            model_name='registrarform',
            name='usuario',
            field=models.CharField(db_column='usuario', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrarform',
            name='contraseña',
            field=models.CharField(db_column='contraseña', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrarform',
            name='correo_us',
            field=models.CharField(db_column='correo', max_length=100),
        ),
    ]
