# Generated by Django 4.2.5 on 2023-10-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_registrarform_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrarform',
            table='Regis',
        ),
    ]
