# Generated by Django 4.2.5 on 2023-10-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_registrarform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrarform',
            table='Registrar',
        ),
    ]
