# Generated by Django 4.2.5 on 2023-10-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cafe_cerveza_corte_empanada_guarnicion_postre_precio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cafe',
        ),
        migrations.DeleteModel(
            name='Cerveza',
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
        migrations.DeleteModel(
            name='Empanada',
        ),
        migrations.DeleteModel(
            name='Guarnicion',
        ),
        migrations.DeleteModel(
            name='Postre',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.DeleteModel(
            name='Refresco',
        ),
        migrations.DeleteModel(
            name='SalsaPasta',
        ),
    ]
