# Generated by Django 4.2.5 on 2023-10-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cafes_cervezas_cortes_empanadas_guarniciones_postres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('Id_general', models.AutoField(primary_key=True, serialize=False)),
                ('precios', models.CharField(db_column='Precios', max_length=100)),
                ('empanadas', models.CharField(db_column='Empanadas', max_length=100)),
                ('cortes', models.CharField(db_column='Cortes', max_length=100)),
                ('guarniciones', models.CharField(db_column='Guarniciones', max_length=100)),
                ('postres', models.CharField(db_column='Postres', max_length=100)),
                ('salsapastas', models.CharField(db_column='SalsaPasta', max_length=100)),
                ('alcohol', models.CharField(db_column='Alcohol', max_length=100)),
                ('cervezas', models.CharField(db_column='Cervezas', max_length=100)),
                ('refrescos', models.CharField(db_column='Refrescos', max_length=100)),
                ('cafes', models.CharField(db_column='Cafes', max_length=100)),
            ],
            options={
                'db_table': 'General',
            },
        ),
        migrations.DeleteModel(
            name='Cafes',
        ),
        migrations.DeleteModel(
            name='Cervezas',
        ),
        migrations.DeleteModel(
            name='Cortes',
        ),
        migrations.DeleteModel(
            name='Empanadas',
        ),
        migrations.DeleteModel(
            name='Guarniciones',
        ),
        migrations.DeleteModel(
            name='Postres',
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
        migrations.DeleteModel(
            name='Refrescos',
        ),
        migrations.DeleteModel(
            name='SalsaPastas',
        ),
    ]
